apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: gonzalorodriguez  # Add the namespace here
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: gonzalorodriguez/token-app:latest
        ports:
        - containerPort: 5000
