apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: gonzalorodriguez  # Add the namespace here
spec:
  type: LoadBalancer  # Use LoadBalancer for cloud environments
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-app
